version: "3.7"

services:
  url-shortener:
	build: ./url-shortener
	container_name: url-shortener
	env_file: ./url-shortener/.env
	depends_on:
  	- db
	volumes:
  	- ./url-shortener/migrations:/usr/src/migrations
	expose:
  	- 80
  
  nginx:
	build: ./nginx
	container_name: nginx
	depends_on:
  	- url-shortener
	ports:
  	- 80:80
  
  db:
	image: postgres
	container_name: db
	env_file: ./url-shortener/.env
	volumes: 
  	- pgdata:/var/lib/postgresql/data
	expose:
  	- 5432

volumes: 
  pgdata:
