"""empty message

Revision ID: 5f92514b99f6
Revises: 
Create Date: 2021-03-18 14:14:27.579830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f92514b99f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table('user',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('created_at', sa.DateTime(), nullable=True),
	sa.Column('updated_at', sa.DateTime(), nullable=True),
	sa.Column('username', sa.String(length=30), nullable=False),
	sa.Column('password_hash', sa.String(length=255), nullable=True),
	sa.Column('is_active', sa.Boolean(), nullable=True),
	sa.Column('is_staff', sa.Boolean(), nullable=True),
	sa.PrimaryKeyConstraint('id')
	)
	op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
	# ### end Alembic commands ###


def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_index(op.f('ix_user_username'), table_name='user')
	op.drop_table('user')
	# ### end Alembic commands ###
